In [1]:
import pandas as pd

from common.config import WIENER_NOKERNEL_DATASET, WIENER_WKERNEL_DATASET, PSEUDOINVERSE_NOKERNEL_DATASET, PSEUDOINVERSE_WKERNEL_DATASET, DEBLURGANV2_DATASET

dfs = {
    'pseudoinverse_nokernel': pd.read_parquet(PSEUDOINVERSE_NOKERNEL_DATASET),
    'pseudoinverse_wkernel': pd.read_parquet(PSEUDOINVERSE_WKERNEL_DATASET),
    'wiener_nokernel': pd.read_parquet(WIENER_NOKERNEL_DATASET),
    'wiener_wkernel': pd.read_parquet(WIENER_WKERNEL_DATASET),
    'deblurganv2': pd.read_parquet(DEBLURGANV2_DATASET)
}

In [2]:
dfs["wiener_nokernel"]

,key,proctime_box,proctime_gaussian,proctime_motion,ssim_box,psnr_box,lpips_box,gmsd_box,ssim_gaussian,psnr_gaussian,lpips_gaussian,gmsd_gaussian,ssim_motion,psnr_motion,lpips_motion,gmsd_motion
0,000000000,0.458832,0.515758,0.462619,0.496839,18.977943,0.126385,0.249297,0.468064,18.702694,0.093637,0.284283,0.334376,13.861960,0.068649,0.312474
1,000000002,0.457824,0.478058,0.460747,0.184690,15.485043,0.072707,0.241003,0.162212,15.053017,0.079676,0.242625,0.093464,13.648773,0.158376,0.273850
2,000000003,0.615560,0.606898,0.601368,0.105265,14.587455,0.077475,0.300390,0.395504,19.595360,0.154698,0.260329,0.185484,15.149970,0.226845,0.299215
3,000000004,0.427569,0.416815,0.414729,0.315277,15.306178,0.231524,0.272371,0.266199,14.633955,0.102267,0.287295,0.164425,12.198738,0.269923,0.294317
4,000000005,0.571736,0.559716,0.558967,0.353146,17.785113,0.162414,0.258377,0.183185,11.047638,0.226223,0.301999,0.251204,15.311221,0.163472,0.253726
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,000001245,0.935081,0.938367,0.921489,0.266700,11.880445,0.036817,0.316571,0.382016,13.020934,0.071874,0.332916,0.217987,7.915343,0.178809,0.373328
946,000001246,1.110227,1.123377,1.078878,0.320874,17.423777,0.289820,0.271511,0.307444,17.347380,0.152111,0.310329,0.108402,11.436147,0.181782,0.303954
947,000001247,1.188854,1.202173,1.159555,0.221787,14.975796,0.071808,0.279396,0.203191,14.047853,0.048440,0.272331,0.100915,10.854823,0.254368,0.317027
948,000001248,0.644407,0.651523,0.633614,0.315127,16.406077,0.289839,0.258532,0.214891,13.571545,0.052846,0.273099,0.125721,9.701543,0.195918,0.313943
949,000001249,0.840287,0.799652,0.783464,0.344261,18.200150,0.224665,0.237262,0.304281,17.787408,0.078611,0.248056,0.121203,12.865656,0.118028,0.290058

In [10]:
results = {
    "method": [],
    "blur_type": [],
    "total_time": [],
    "speed": []
}

cols = ["proctime_box", "proctime_gaussian", "proctime_motion"]

for method in dfs.keys():
    n = dfs[method].shape[0]

    for col in cols:
        total_time = dfs[method][col].sum()
        speed = dfs[method][col].mean()

        results["method"].append(method)
        results["blur_type"].append(col.split("_")[1])
        results["total_time"].append(total_time)
        results["speed"].append(speed)

df = pd.DataFrame.from_dict(results)

In [11]:
df

                    method blur_type  total_time     speed
0   pseudoinverse_nokernel       box  676.660725  0.712274
1   pseudoinverse_nokernel  gaussian  672.559634  0.707958
2   pseudoinverse_nokernel    motion  680.524854  0.716342
3    pseudoinverse_wkernel       box  676.660725  0.712274
4    pseudoinverse_wkernel  gaussian  672.559634  0.707958
5    pseudoinverse_wkernel    motion  680.524854  0.716342
6          wiener_nokernel       box  635.861859  0.669328
7          wiener_nokernel  gaussian  646.899744  0.680947
8          wiener_nokernel    motion  632.337499  0.665618
9           wiener_wkernel       box  578.899451  0.609368
10          wiener_wkernel  gaussian  580.611288  0.611170
11          wiener_wkernel    motion  575.135847  0.605406
12             deblurganv2       box  263.433838  0.277299
13             deblurganv2  gaussian  260.581364  0.274296
14             deblurganv2    motion  258.537860  0.272145